### ISSUE TITLE
移除 IE 10 及以上 input 自带的 clear button 以及 type="password" 带有的 icon 

### ISSUE THREAD

**Issue by simaQ** [simaQ/cssfun#5]
### 问题
![rm](https://cloud.githubusercontent.com/assets/6628666/9102004/3c4d6cb2-3c20-11e5-9c6f-613e71d992bc.png)

### Solution
```css
::-ms-clear {
   display: none;
}

::-ms-reveal {
   display: none;
}
```

see more:
- http://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs
- http://msdn.microsoft.com/en-us/library/windows/apps/hh465740.aspx
